import re


MANUFACTURERS = [
    "Aguila",
    "Ammo Inc",
    "Armscor",
    "Atlanta Arms",
    "ATS Ammunition",
    "Atomic",
    "Barnaul",
    "Barnes",
    "Belom",
    "Black Hills",
    "Blazer",
    "Buffalo Bore",
    "Buffalo Cartridge",
    "Browning",
    "Cascade",
    "CCI",
    "Century Arms",
    "Colt",
    "CorBon",
    "Doubletap Ammunition",
    "Eley",
    "Federal",
    "Fiocchi",
    "First Breach",
    "Fort Scott",
    "Frontier",
    "G2 Research",
    "G9 Defense",
    "Geco",
    "Grizzly Cartridge",
    "Herter's",
    "Hornady",
    "HSM",
    "Hyperion Munitions",
    "ICC",
    "Inceptor",
    "Independence",
    "Koenig",
    "Lapua",
    "Lehigh Defense",
    "Liberty",
    "Magtech",
    "Maxim Defense",
    "MAXXTech",
    "Norma",
    "Nosler",
    "NovX",
    "Paraklese",
    "Piney Mountain",
    "PMC",
    "PPU",
    "Prvi Partizan",
    "Red Army Standard",
    "Remington",
    "RWS",
    "Sellier & Bellot",
    "Sierra",
    "Sig Sauer",
    "Sinterfire",
    "SK Ammunition",
    "Speer",
    "Sports South",
    "Sterling",
    "Streak",
    "TulAmmo",
    "Underwood",
    "Walther",
    "Wilson Combat",
    "Winchester",
    "Wolf",
    "ZSR",
]


def get_manufacturer(title):
    pattern = "|".join(re.escape(manufacturer) for manufacturer in MANUFACTURERS)
    match = re.search(pattern, title, re.IGNORECASE)
    return match.group() if match else None
