import re


MANUFACTURERS = {
    "1776 USA": ["1776 usa"],
    "2A Patriot Sports": ["2a patriot"],
    "Aguila Ammunition": ["aguila"],
    "American Ammunition Company": ["aac", "american ammunition company"],
    "American Quality Ammunition": ["american quality", "aqa"],
    "American Sniper Ammunition": ["american sniper"],
    "Ammo Bro": ["ammo bro"],
    "Ammo Incorporated": ["ammo inc", "ammo, inc"],
    "Armscor": ["armscor", "arms"],
    "Arsenal Inc": ["arsenal"],
    "Atlanta Arms": ["atlanta arms"],
    "ATS Ammunition": ["ats ammunition"],
    "Atomic": ["atomic"],
    "Barnaul": ["barnaul"],
    "Barnes": ["barnes"],
    "Belom": ["belom"],
    "Black Hills": ["black hills"],
    "Blazer": ["blazer"],
    "BPS": ["bps"],
    "Buffalo Bore": ["buffalo bore"],
    "Buffalo Cartridge": ["buffalo cartridge"],
    "Bullets 1st": ["bullets 1st"],
    "Browning": ["browning", "brna"],
    "BVAC": ["bvac"],
    "Capital Cartridge": ["capital cartridge"],
    "Cascade": ["cascade"],
    "CCI": ["cci", "blazer"],
    "Century Arms": ["century arms"],
    "Colt": ["colt"],
    "CorBon": ["corbon", "cor-bon"],
    "Defiant Munitions": ["defiant"],
    "Dignity Defense": ["dignity defense", "jello shot"],
    "Doubletap Ammunition": ["doubletap ammunition", "dbltap", "dtap"],
    "Eley": ["eley"],
    "Exakt": ["exakt"],
    "Federal": ["fed", "american eagle", "amer eagle"],
    "Fiocchi": ["fiocchi", "fio"],
    "First Breach": ["first breach"],
    "Fort Scott Munitions": ["fort scott", "fsm"],
    "Freedom Munitions": ["freedom munitions", "freedom"],
    "Frontier": ["frontier"],
    "G2 Research": ["g2 research", "g2r"],
    "G9 Defense": ["g9 defense"],
    "Geco": ["geco"],
    "Grizzly Cartridge": ["grizzly cartridge"],
    "Happy Valley": ["happy valley"],
    "Herter's": ["herter"],
    "Hornady": ["hornady", "hrndy", "horn"],
    "HSM": ["hsm"],
    "Hyperion Munitions": ["hyperion munitions"],
    "ICC": ["icc"],
    "Igman": ["igman"],
    "Inceptor": ["inceptor"],
    "Independence": ["independence"],
    "Keystone Munitions": ["keystone munitions"],
    "Koenig": ["koenig"],
    "Komando": ["komando"],
    "Lahab Munitions": ["lahab"],
    "Lapua": ["lapua"],
    "LAX Ammunition": ["lax ammunition", "lax ammo"],
    "Lehigh Defense": ["lehigh defense"],
    "Liberty": ["liberty"],
    "Magtech": ["magtech"],
    "MFS": ["mfs"],
    "Maxim Defense": ["maxim"],
    "MAXXTech": ["maxxtech"],
    "New Republic": ["new republic"],
    "Norma": ["norma"],
    "Nosler": ["nosler", "noslr"],
    "NovX": ["novx"],
    "Oak Island": ["oak island"],
    "OZK": ["ozk"],
    "Paraklese": ["paraklese"],
    "Patriot Defense": ["patriot defense"],
    "Piney Mountain": ["piney mountain"],
    "PMC": ["pmc"],
    "PPU": ["prvi partizan", "ppu"],
    "Precision One": ["precision one"],
    "Red Army Standard": ["red army standard", "cia"],
    "Remington": ["remington"],
    "RWS": ["rws"],
    "Scorpio": ["scorpio"],
    "Sellier & Bellot": ["sellier", "s&b", "bellot"],
    "Sergeant Major Munition": ["sergeant"],
    "Sierra": ["sierra"],
    "Sig Sauer": ["sig sauer", "sig"],
    "Sinterfire": ["sinterfire"],
    "SK Ammunition": ["sk ammunition"],
    "Speer": ["speer", "lawman", "gold dot"],
    "Sports South": ["sports south"],
    "Stelth": ["stelth"],
    "Sterling Ammunition": ["sterling"],
    "Streak Ammunition": ["streak"],
    "Stryker": ["stryker"],
    "STV Technology": ["stv technology", "scorpio"],
    "Troy USA": ["troy"],
    "TulAmmo": ["tulammo", "tula"],
    "Turan": ["turan"],
    "Underwood": ["underwood"],
    "US Cartridge": ["us cartridge", "usc"],
    "Vairog": ["vairog"],
    "Venom": ["venom"],
    "Veteran Ammo": ["veteran ammo"],
    "Walther": ["walther"],
    "Wilson Combat": ["wilson combat"],
    "Winchester": ["win", "winchester"],
    "Wolf": ["wolf"],
    "ZSR": ["zsr"],
    "ZVS": ["zvs"],
}


def get_manufacturer(title):
    pattern = "|".join(
        re.escape(variation)
        for manufacturer, variations in MANUFACTURERS.items()
        for variation in variations
    )
    match = re.search(pattern, title.lower(), re.IGNORECASE)
    if match:
        for manufacturer, variations in MANUFACTURERS.items():
            if match.group() in variations:
                return manufacturer
    return None
