import re


MANUFACTURERS = [
    "Aguila",
    "Ammo Inc",
    "Armscor",
    "Atlanta Arms",
    "ATS Ammunition",
    "Atomic",
    "Barnaul",
    "Barnes",
    "Black Hills",
    "Blazer",
    "Buffalo Bore",
    "Browning",
    "Cascade",
    "CCI",
    "Century Arms",
    "Colt",
    "CorBon",
    "Doubletap Ammunition",
    "Eley",
    "Federal",
    "Fiocchi",
    "First Breach",
    "Fort Scott",
    "Frontier",
    "G2 Research",
    "G9 Defense",
    "Geco",
    "Grizzly Cartridge",
    "Hornady",
    "HSM",
    "Hyperion Munitions",
    "ICC",
    "Independence",
    "Koenig",
    "Lapua",
    "Lehigh Defense",
    "Liberty",
    "Magtech",
    "Maxim Defense Industries",
    "MAXXTech",
    "Norma",
    "Nosler",
    "NovX",
    "Paraklese",
    "Piney Mountain",
    "PMC",
    "PPU",
    "Prvi Partizan",
    "Red Army Standard",
    "Remington",
    "RWS",
    "Sellier & Bellot",
    "Sierra",
    "Sig Sauer",
    "Sinterfire",
    "SK Ammunition",
    "Speer",
    "Sports South",
    "Tula",
    "Underwood",
    "Walther",
    "Wilson Combat",
    "Winchester",
    "Wolf",
]


def get_manufacturer(title):
    pattern = "|".join(re.escape(manufacturer) for manufacturer in MANUFACTURERS)
    match = re.search(pattern, title, re.IGNORECASE)
    return match.group() if match else None
